version: "2"

services:
  #
  # Host -> smtp
  # Port -> 1025
  #
  mailhog:
      image: mailhog/mailhog
      container_name: mailhog
      ports:
        - "1025:1025"
        - "8025:8025"

  activemq:
      image: rmohr/activemq
      ports:
        - "8161:8161"
        - "61616:61616"
