app:
  jwt:
    secret: JWTSecretKey
    expiration: 600000

spring:
  h2:
    console:
      enabled: true
      path: /h2/

  datasource:
    generate-unique-name: false

  jpa:
    show-sql: false

  mail:
    protocol: smtp
    host: localhost
    port: 1025
    username:
    password:
    smtp:
      auth: false

  jackson:
    time-zone: UTC

activemq:
  broker-url: tcp://localhost:61616
  user: admin
  password: admin

destination:
  user:
    registration: user.created.email

server:
  port: 8000